# Shared user-level editor configuration; importing this module does not manage macOS settings.
{ config, pkgs, pkgsUnstable, dotfilesRoot, ... }:
let
  # Keep parser grammars, queries and their plugin on the same pinned package set.
  treesitter = pkgsUnstable.vimPlugins.nvim-treesitter.withPlugins (g: with g; [
    bash c css diff html javascript jsdoc json lua luadoc luap
    markdown markdown_inline nix python query regex toml tsx typescript
    vim vimdoc xml yaml
  ]);
  parsers = pkgs.symlinkJoin {
    name = "workstation-neovim-parsers";
    paths = treesitter.dependencies;
  };
in {
  programs.neovim = {
    enable = true;
    package = pkgs.neovim-unwrapped;
    withNodeJs = false;
    withPython3 = false;
    withRuby = false;
    # Put provider settings in the wrapper; the repository owns the LazyVim init.lua.
    sideloadInitLua = true;
  };
  home.packages = with pkgs; [
    fd fzf nodejs_24
    vtsls pyright ruff python3
    lua-language-server nil bash-language-server shellcheck
    vscode-langservers-extracted yaml-language-server taplo
    prettier stylua shfmt nixfmt
  ];
  home.file.".config/nvim".source =
    config.lib.file.mkOutOfStoreSymlink "${dotfilesRoot}/home/.config/nvim";
  home.file.".config/nvim-nix.lua".text = ''
    -- Generated by modules/editor.nix; edit the declaration, not this file.
    return {
      treesitter = "${treesitter}",
      textobjects = "${pkgsUnstable.vimPlugins.nvim-treesitter-textobjects}",
      parsers = "${parsers}",
    }
  '';
}
